{% set name = "scarab" %}
{% set version = "0.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8,<3.12
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8,<3.12
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - umap-learn
    - hdbscan
    - sourmash
    - pyfastx
    - scikit-bio
    - tqdm
    - minimap2
    - samtools
    - metabat2
    - bbmap

test:
  commands:
    - scarab info -h

about:
  home: https://github.com/hallamlab/scarab
  license: GPL-3.0
  license_file: LICENSE
  summary: SCARAB recruits metagenomic reads using single-cell amplified genomes as references.

extra:
  recipe-maintainers:
    - hallamlab
